### ISSUE TITLE
SIGSEGV on startup due to uri parse error in identifer-registration.yaml

### ISSUE THREAD

**Issue by edamrose** [Kopano-dev/konnect#9]
Konnectd will crash on startup when parsing an invalid redirect uri exists in identifier-registration.yaml:

```
time="2019-06-12T15:45:25Z" level=debug msg="parsing identifier registration conf from /etc/kopano/identifier-registration.yaml"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x843381]

goroutine 1 [running]:
stash.kopano.io/kc/konnect/identity/clients.(*Registry).Register(0xc00007c6e0, 0xc000094dc0, 0x0, 0x0)
        /var/lib/jenkins/jobs/kc_konnect/branches/master/workspace/.gopath/src/stash.kopano.io/kc/konnect/identity/clients/registry.go:118 +0x5d1
stash.kopano.io/kc/konnect/identity/clients.NewRegistry(0xb633e0, 0xc00002a058, 0xc0000d2500, 0x7fffbf14636a, 0x28, 0xb6f460, 0xc00005e960, 0x0, 0xc00010bb50, 0x40b689)
        /var/lib/jenkins/jobs/kc_konnect/branches/master/workspace/.gopath/src/stash.kopano.io/kc/konnect/identity/clients/registry.go:74 +0x146
main.newManagers(0xb633e0, 0xc00002a058, 0xc000090a00, 0xc0000e8ff0, 0xc00010bba0, 0x68)
        src/stash.kopano.io/kc/konnect/cmd/konnectd/managers.go:55 +0x2d3
main.(*bootstrap).setup(0xc000090a00, 0xb633e0, 0xc00002a058, 0x1, 0xc00005e960)
        src/stash.kopano.io/kc/konnect/cmd/konnectd/bootstrap.go:322 +0x5a
main.serve(0xc00008f900, 0xc0000d2300, 0x1, 0x8, 0x4, 0xa7c182)
        src/stash.kopano.io/kc/konnect/cmd/konnectd/serve.go:102 +0x332
main.commandServe.func1(0xc00008f900, 0xc0000d2300, 0x1, 0x8)
        src/stash.kopano.io/kc/konnect/cmd/konnectd/serve.go:46 +0x53
stash.kopano.io/kc/konnect/vendor/github.com/spf13/cobra.(*Command).execute(0xc00008f900, 0xc0000d2280, 0x8, 0x8, 0xc00008f900, 0xc0000d2280)
        /var/lib/jenkins/jobs/kc_konnect/branches/master/workspace/.gopath/src/stash.kopano.io/kc/konnect/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
stash.kopano.io/kc/konnect/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xf96bc0, 0xc000051f70, 0x1, 0x1)
        /var/lib/jenkins/jobs/kc_konnect/branches/master/workspace/.gopath/src/stash.kopano.io/kc/konnect/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
stash.kopano.io/kc/konnect/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /var/lib/jenkins/jobs/kc_konnect/branches/master/workspace/.gopath/src/stash.kopano.io/kc/konnect/vendor/github.com/spf13/cobra/command.go:800
main.main()
        src/stash.kopano.io/kc/konnect/cmd/konnectd/main.go:31 +0xb8
```

I would expect no crash but that an error is logged, and the client entry is simply ignored.

small identifier-registration.yaml reproducer (two `=` in front of redirect uri):
```
clients:
- application_type: web
  id: wordpress-ucs
  name: Wordpress
  redirect_uris:
  - ==https://ucsmaster.mydomain.intranet/wordpress/wp-admin/admin-ajax.php
  secret: averysecretpassword
  trusted: true
```

**Comment by longsleep** [comment]
Thanks for reporting, i just pushed a fix - will be included in the next release.
